env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  map_name: "n100c20000d21s*l100"
  n_agents: 100
  task_type: "CapacityHigh"
  mode: train
  time_limit: 100
  reward: "lambda"
